### ISSUE TITLE
connection error!

### ISSUE THREAD

**Issue by phial3** [rmqtt-rs/rmqtt#2]
![image](https://user-images.githubusercontent.com/27754514/150630249-8f5b4975-8b32-4d3f-b5e9-4d89dd615db2.png)

**Comment by rmqtt-rs** [comment]
You can close the "rmqtt-auth-http" plugin first. it is in configuration file "rmqtt.toml" .

##--------------------------------------------------------------------
## Plugins
##--------------------------------------------------------------------
#Plug in configuration file directory
plugins.dir = "../../../rmqtt-plugins/"
#Plug in started by default, when the mqtt server is started
plugins.default_startups = [
    "rmqtt-cluster-broadcast",
    #"rmqtt-auth-http",
    "rmqtt-web-hook"
]

For example:
#"rmqtt-auth-http",
